---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice01
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice01
    spec:
      containers:
      - name: mymicroservice
        image: stephenwalter/microservice01:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: microservice01
---
apiVersion: v1
kind: Service
metadata:
  name: microservice01
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: microservice01
